GuildCars.UI/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class InventoryController : Controller
    {
        [HttpGet]
        public ActionResult New()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Used()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Detail()
        {
            return View();
        }
    }
}

GuildCars.UI/Controllers/ReportController.cs
using GuildCars.Models.Interface;
using GuildCars.Datas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GuildCars.Models.ViewModels;

namespace GuildCars.UI.Controllers
{
    [Authorize(Roles = "admin")]
    public class ReportController : Controller
    {
        ICar _repo = CarFactory.Create();
        public ActionResult Sale()
        {
            SaleReportVMPage model = new SaleReportVMPage();
            model.SetUserItems(_repo.GetUserList());
            DateTime N = DateTime.Now;
            model.FDate = null;// DateTime.MinValue;// DateTime.Parse(N.Month + "/01/" + N.Year);
            model.TDate = null;// DateTime.MaxValue;// DateTime.Parse(N.Month + "/01/" + N.Year);
            model.SaleReportVM = _repo.GetSaleReport("", DateTime.Parse("01/01/1900"), DateTime.Parse("01/01/2500"));
            return View(model);
        }
        [HttpPost]
        public ActionResult Sale(SaleReportVMPage model)
        {
            if(model.FDate < DateTime.Parse("01/01/1900"))
            {
                model.FDate = DateTime.Parse("01/01/1900");
            }

            if (model.TDate > DateTime.Parse("12/31/2500"))
            {
                model.TDate = DateTime.Parse("12/31/2500");
            }

            if (string.IsNullOrEmpty(model.UserId))
            {
                model.UserId = "";
            }
            model.SetUserItems(_repo.GetUserList());
            model.SaleReportVM = _repo.GetSaleReport(model.UserId, DateTime.Parse("01/01/1900"), DateTime.Parse("12/31/2500"));
            return View(model);
        }

        public ActionResult Inventory()
        {
            var result = _repo.GetInventoryReport();
            return View(result);
        }
        
    }
}

GuildCars.UI/Controllers/ResetPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GuildCars.Models.ViewModels;
using GuildCars.Models.Interface;
using GuildCars.Datas;

namespace SCMS.UI.Controllers
{
    [Authorize(Roles = "admin,sale")]
    public class ResetPasswordController : Controller
    {
        ICar _repo = CarFactory.Create();

        // GET: ResetPassword
        public ActionResult ResetPassword()
        {
            ResetPasswordVM model = new ResetPasswordVM();
            model.UserName = CurrentUser.User.UserName;
            return View(model);
        }

        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordVM model)
        {
            if (ModelState.IsValid)
            {
                if (_repo.ChangePassword(model.UserName, model.Password, model.NewPassword))
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("PasswordHash", "Incorrect password");
                }
            }

            return View(model);
        }
    }
}

GuildCars.UI/Controllers/SpecialController.cs
using GuildCars.Models;
using GuildCars.Models.Interface;
using GuildCars.Models.ViewModels;
using GuildCars.Datas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class SpecialController : Controller
    {
        ICar _repo = CarFactory.Create();

        [HttpGet]
        public ActionResult Show()
        {
            List<SpecialVM> model = _repo.GetSpecialVMList();
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult List()
        {
            List<SpecialVM> model = _repo.GetSpecialVMList();
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Add()
        {
            SpecialVM model = _repo.ConvertSpecialToVM(new Special());
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Add(SpecialVM model)
        {
            if (!String.IsNullOrEmpty(model.Description) && !String.IsNullOrEmpty(model.Title))
            {
                model = _repo.AddSpecial(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else if (String.IsNullOrEmpty(model.Title))
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Title is required";
            }
            else
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Edit(int specialId)
        {
            SpecialVM model = _repo.ConvertSpecialToVM(_repo.GetSpecialById(specialId));
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(SpecialVM model)
        {
            if (!String.IsNullOrEmpty(model.Description) && !String.IsNullOrEmpty(model.Title))
            {
                model = _repo.UpdateSpecial(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else if (string.IsNullOrEmpty(model.Title))
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Title is required";
            }
            else
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Delete(int specialId)
        {
            SpecialVM model = _repo.ConvertSpecialToVM(_repo.GetSpecialById(specialId));
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Delete(SpecialVM model)
        {
            model.Result = _repo.DeleteSpecial(model);
            if (model.Result.Success)
            {
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }
        }
    }
}

GuildCars.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDL4qC02sD3ZZL36YbYct2aeawL5nwSP1o&callback=initMap" type="text/javascript"></script>
    <link href="~/Content/car.css" rel="stylesheet" />
</head>

<body style="position: relative !important;">
    <div id="nav" class="navbar navbar-inverse navbar-fixed-top" style="background-color:white;">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a href=""><span class="glyphicon glyphicon-home"></span></a></li>
                <li>@Html.ActionLink("Home", "Home", "Home")</li>
                <li>@Html.ActionLink("New Inventory", "New", "Inventory")</li>
                <li>@Html.ActionLink("Used Inventory", "Used", "Inventory")</li>
                <li>@Html.ActionLink("Specials", "Show", "Special")</li>
                <li>@Html.ActionLink("Contact", "Add", "Contact")</li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Sale", "List", "Sale")</li>
                    <li>@Html.ActionLink("Change Password", "ResetPassword", "ResetPassword")</li>


                    if (User.IsInRole("admin"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Admin
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Vehicle", "List", "Vehicle")</li>
                                <li>@Html.ActionLink("Special", "List", "Special")</li>
                                <li  role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Contact", "List", "Contact")</li>
                                <li>@Html.ActionLink("Sale Report", "Sale", "Report")</li>
                                <li>@Html.ActionLink("Inventory Report", "Inventory", "Report")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Make", "List", "Make")</li>
                                <li>@Html.ActionLink("Model", "List", "Model")</li>
                                <li>@Html.ActionLink("User", "List", "User")</li>

                            </ul>
                        </li>
                    }
                    <li>@Html.ActionLink("Log Out", "LogOut", "Auth")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Log In", "LogIn", "Auth")</li>
                }
            </ul>
        </div>
    </div>
    
    <div class="container body-content" style="margin-top:50px">
        @RenderBody()
    </div>


    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/car.js"></script>
</body>
</html>