GuildCars.UI/Controllers/MakeController.cs
using GuildCars.Models;
using GuildCars.Models.Interface;
using GuildCars.Models.ViewModels;
using GuildCars.Datas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    [Authorize(Roles = "admin")]
    public class MakeController : Controller
    {
        ICar _repo = CarFactory.Create();

        [HttpGet]
        public ActionResult List()
        {
            List<MakeVM> model = _repo.GetMakeVMList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(_repo.ConvertMakeToVM(new Make()));
        }

        [HttpPost]
        public ActionResult Add(MakeVM model)
        {
            if (!string.IsNullOrEmpty(model.Description))
            {
                model.AddUserId = CurrentUser.User.Id;
                model.AddDate = DateTime.Now;
                model = _repo.AddMake(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }                
            }
            else
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int makeId)
        {
            MakeVM model = _repo.ConvertMakeToVM(_repo.GetMakeById(makeId));
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(MakeVM model)
        {
            if (!string.IsNullOrEmpty(model.Description))
            {
                model.EditUserId = CurrentUser.User.Id;
                model.EditDate = DateTime.Now;
                model = _repo.UpdateMake(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int makeId)
        {
            MakeVM model = _repo.ConvertMakeToVM(_repo.GetMakeById(makeId));
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(MakeVM model)
        {
            model.Result = _repo.DeleteMake(model);
            if (model.Result.Success)
            {
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }
        }
    }
}

GuildCars.UI/Controllers/ModelController.cs
using GuildCars.Models;
using GuildCars.Models.Interface;
using GuildCars.Models.ViewModels;
using GuildCars.Datas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    [Authorize(Roles = "admin")]
    public class ModelController : Controller
    {
        ICar _repo = CarFactory.Create();

        [HttpGet]
        public ActionResult List()
        {
            List<ModelVM> model = _repo.GetModelVMList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ModelVM model = _repo.ConvertModelToVM(new Model());
            model.SetMakeItems(_repo.GetMakeList());
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(ModelVM model)
        {
            if (!String.IsNullOrEmpty(model.Description) && model.MakeId > 0)
            { 
                model.AddUserId = CurrentUser.User.Id;
                model.AddDate = DateTime.Now;
                model = _repo.AddModel(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else if (String.IsNullOrEmpty(model.Description))
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }
            else if (model.MakeId <= 0)
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Please choose make";
            }

            model.SetMakeItems(_repo.GetMakeList());
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int modelId)
        {
            ModelVM model = _repo.ConvertModelToVM( _repo.GetModelById(modelId));
            model.SetMakeItems(_repo.GetMakeList());
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ModelVM model)
        {
            if (!String.IsNullOrEmpty(model.Description) && model.MakeId > 0)
            {
                model.EditUserId = CurrentUser.User.Id;
                model.EditDate = DateTime.Now;
                model = _repo.UpdateModel(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else if(String.IsNullOrEmpty(model.Description)){
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }
            else if(model.MakeId <= 0){
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Please choose make";
            }
            model.Result.Success = false;
            model.SetMakeItems(_repo.GetMakeList());
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int modelId)
        {
            ModelVM model = _repo.ConvertModelToVM(_repo.GetModelById(modelId));
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(ModelVM model)
        {
            model.Result = _repo.DeleteModel(model);
            if (model.Result.Success)
            {
                return RedirectToAction("List");
            }
            else
            {                
                return View(model);
            }
        }
    }
}

GuildCars.UI/Controllers/SpecialController.cs
using GuildCars.Models;
using GuildCars.Models.Interface;
using GuildCars.Models.ViewModels;
using GuildCars.Datas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class SpecialController : Controller
    {
        ICar _repo = CarFactory.Create();

        [HttpGet]
        public ActionResult Show()
        {
            List<SpecialVM> model = _repo.GetSpecialVMList();
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult List()
        {
            List<SpecialVM> model = _repo.GetSpecialVMList();
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Add()
        {
            SpecialVM model = _repo.ConvertSpecialToVM(new Special());
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Add(SpecialVM model)
        {
            if (!String.IsNullOrEmpty(model.Description) && !String.IsNullOrEmpty(model.Title))
            {
                model = _repo.AddSpecial(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else if (String.IsNullOrEmpty(model.Title))
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Title is required";
            }
            else
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Edit(int specialId)
        {
            SpecialVM model = _repo.ConvertSpecialToVM(_repo.GetSpecialById(specialId));
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(SpecialVM model)
        {
            if (!String.IsNullOrEmpty(model.Description) && !String.IsNullOrEmpty(model.Title))
            {
                model = _repo.UpdateSpecial(model);
                if (model.Result.Success)
                {
                    return RedirectToAction("List");
                }
            }
            else if (string.IsNullOrEmpty(model.Title))
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Title is required";
            }
            else
            {
                model.Result = _repo.ReturnSuccess();
                model.Result.Success = false;
                model.Result.ErrorMessage = "Description is required";
            }

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Delete(int specialId)
        {
            SpecialVM model = _repo.ConvertSpecialToVM(_repo.GetSpecialById(specialId));
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Delete(SpecialVM model)
        {
            model.Result = _repo.DeleteSpecial(model);
            if (model.Result.Success)
            {
                return RedirectToAction("List");
            }
            else
            {
                return View(model);
            }
        }
    }
}

GuildCars.UI/Views/Special/Add.cshtml
@model GuildCars.Models.ViewModels.SpecialVM

@{
    ViewBag.Title = "Add Special";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Add Special</h3>        
    </div>
</div>
<div class="row">
    <div class="col-xs-3">
        @using (Html.BeginForm("Add", "Special", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmUpload" }))
        {
            <div class="form-group">
                <label>Title</label>
                @Html.TextBoxFor(m=>m.Title, new { @class = "form-control", placeholder = "Title"})
                <label>Description</label>
                @Html.TextAreaFor(s => s.Description, new { @class = "form-control", placeholder = "Description" })
                <label>Display Start Date</label>@Html.ValidationMessageFor(m=>m.FDate)
                @Html.EditorFor(m => m.FDate, null, new { @class = "form-control" })
                <label>Display End Date</label>@Html.ValidationMessageFor(m => m.TDate)
                @Html.EditorFor(m => m.TDate, null, new { @class = "form-control" })

                <div class="form-group">
                    <label>Select File:</label>
                    @Html.TextBoxFor(m => m.UploadFile, new { type = "file", @class = "form-control" })
                </div>
                
                @if (!@Model.Result.Success)
                {
                    <div class="divError">
                        <b>
                            @Html.DisplayFor(m => m.Result.ErrorMessage)
                        </b>
                    </div>
                }
                <div class="divSave">
                    <button type="submit" class="btn btn-primary">Save</button>
                    @Html.ActionLink("Cancel", "List", "Special", null, new { @class = "btn btn-info" })
                </div>
            </div>
        }
    </div>
</div>      

GuildCars.UI/Views/Special/Delete.cshtml
@model GuildCars.Models.ViewModels.SpecialVM
@{
    ViewBag.Title = "Delete Special";
}

<div class="row">
    <div class="col-xs-4">
        <h3>Delete Special</h3>
        @*@Html.ActionLink("Return to List", "List", "Make")*@
    </div>
</div>
<div class="row">
    <div class="col-xs-4">
        @using (Html.BeginForm("Delete", "Special", FormMethod.Post))
        {
            @Html.HiddenFor(c => c.SpecialId)
            <p>Are you sure that you wish to delete @Html.DisplayFor(c=>c.Description)?</p>
            if (!@Model.Result.Success)
            {
                <div class="divError">
                    <b>
                        @Html.DisplayFor(m => m.Result.ErrorMessage)
                    </b>
                </div>
            }
            <div class="divSave">
                <button type="submit" class="btn btn-danger">Delete</button>
                @Html.ActionLink("Cancel", "List", "Special", null, new { @class = "btn btn-info" })
            </div>
        }
    </div>
</div>     

GuildCars.UI/Views/Special/Edit.cshtml
@model GuildCars.Models.ViewModels.SpecialVM

@{
    ViewBag.Title = "Edit Special";
}

<div class="row">
    <div class="col-xs-12">
        <h3>Edit Special</h3>
        @*@Html.ActionLink("Return to List", "List", "Make")*@
    </div>
</div>
<div class="row">
    <div class="col-xs-3">
        @using (Html.BeginForm("Edit", "Special", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmUpload" }))
        {
            <div class="form-group">
                @Html.HiddenFor(m => m.SpecialId)
                <label>Title</label>
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "Title" })
                <label>Description</label>
                @Html.TextAreaFor(s => s.Description, new { @class = "form-control", placeholder = "Description" })                
                <label>Display Start Date</label>@Html.ValidationMessageFor(m => m.FDate)
                @Html.EditorFor(m => m.FDate, null, new { @class = "form-control" })
                <label>Display End Date</label>@Html.ValidationMessageFor(m => m.TDate)
                @Html.EditorFor(m => m.TDate, null, new { @class = "form-control" })


                <div class="form-group">
                    <label>Select File:</label>
                    @Html.TextBoxFor(m => m.UploadFile, new { type = "file", @class = "form-control" })
                </div>


                @if (!@Model.Result.Success)
                {
                    <div class="divError">
                        <b>
                            @Html.DisplayFor(m => m.Result.ErrorMessage)
                        </b>
                    </div>
                }
                <div class="divSave">
                    <button type="submit" class="btn btn-primary">Save</button>
                    @Html.ActionLink("Cancel", "List", "Model", null, new { @class = "btn btn-info" })
                </div>
            </div>
        }
    </div>
</div>      

GuildCars.UI/Views/Special/List.cshtml
@model List<GuildCars.Models.ViewModels.SpecialVM>

@{
    ViewBag.Title = "Special";
}

<div class="row">
    <div class="col-xs-12">
        <h2>Special</h2>
        @Html.ActionLink("Add Special", "Add", "Special", null, new { @class = "btn btn-primary" })
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped" style="width: auto;">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>                    
                    <th>Display Start</th>
                    <th>Display End</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var c in Model)
                {
                    <tr>
                        <td>@c.Title</td>
                        <td>@c.Description</td>
                        <td>@c.FDate.Value.ToString("MMMM dd, yyyy")</td>
                        <td>@c.TDate.Value.ToString("MMMM dd, yyyy")</td>
                        <td>@Html.ActionLink("Edit", "Edit", "Special", new { specialId = c.SpecialId }, null)</td>
                        <td>@Html.ActionLink("Delete", "Delete", "Special", new { specialId = c.SpecialId }, null)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

GuildCars.UI/Views/Special/Show.cshtml
@model IEnumerable<GuildCars.Models.ViewModels.SpecialVM>
@{
    ViewBag.Title = "Show";
}

<div class="row">
    <div class="col-xs-12">
        <h2>Special</h2>
        @*@Html.ActionLink("Return home", "Home", "Home")*@
    </div>
</div>

<div class="container">
    @foreach(var s in Model)
    {
        <div class="row divShow">
            <div class="col-xs-2">    
                <img src=@s.ImageSrc alt=@s.Title class="imgShow" />
                @*@if (@s.Image != null)
                {                    
                    <img src="data:image;base64,@System.Convert.ToBase64String(s.Image)" alt=@s.Description class="imgShow"/>
                }
                else
                {
                    <img src="http://localhost:50635/Content/Images/special.jpg" alt="special events.jpg" class="imgShow"/>
                }*@
            </div>
            <div class="col-xs-10">
                <b>@s.Title</b><br />
                <span>@s.Description</span>
            </div>
        </div>
        
    }
</div>